version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    volumes:
      - ./frontend:/app/frontend  # Mount frontend directory
      - ./backend:/app/backend    # Mount backend directory
    ports:
      - "3000:3000"