name: publish

# Trigger on push events to any branch
on:
  push:
    branches:
      - '*'

jobs:
  publish-leap24-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
        
      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build . --tag ghcr.io/sandramsc/leap-hackathon-frontend:latest
          docker push ghcr.io/sandramsc/leap-hackathon-frontend:latest

      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build . --tag ghcr.io/sandramsc/leap-hackathon-backend:latest
          docker push ghcr.io/sandramsc/leap-hackathon-backend:latest
